### ISSUE TITLE
Flicker in spout receiver 

### ISSUE THREAD

**Issue by cloaking3000** [keijiro/KlakSpout#37]
I am using Resolume 6 to send video onto geometry using spout receiver and it is strobing inside unity.  I thought was an issue with HDRP but also getting in standard.  Any ideas how to fix this? 
Also it used to work, I am currently using unity 2018.3.of2

Thanks so much (:

**Comment by keijiro** [comment]
Please check if it reproduces with a simple project, like the sample scene in this repository.

**Comment by cloaking3000** [comment]
I've tested it in a basic startup 3d project with no additions besides spout.  I have installed a few different version of unity and the issue persists, however I can't find sample scene in the project

**Comment by cloaking3000** [comment]
I tried installing resolume and unity on a new computer and the issue is still there.  I tried disabling v-sync and a few other graphics and changing the frame rate etc

**Comment by Esam-Bustaty** [comment]
I had (probably) the same problem and I think I got it.

To reproduce all you need is a receiver with `targetRenderer` but WITHOUT `targetTexture`.

I tested on Unity 2018.2 and 2019.1, it happened only on 2019.1.

A warning is logged a lot saying `Releasing render texture that is set to be RenderTexture.active!`.

I found 2 workarounds:
Either change [this](https://github.com/keijiro/KlakSpout/blob/e70b2fd0978ee31f9aecaa04b900f91865527535/Assets/Klak/Spout/Runtime/SpoutReceiver.cs#L145) line (looks familiar? ;) to
`Util.Destroy(_receivedTexture); _receivedTexture = null;`

Or delete lines 16-18 in `Utility.cs` so that `Utils.Destroy()` always executes `DestroyImmediate`

Both solutions work but I opted for the first since it has less side-effects, I don't know what's different in 2019 that makes this not work, but I think it has something to do with when `Destroy` actually destroys objects.

**Comment by Esam-Bustaty** [comment]
I also just tried a third solution which is to modify `Utils.Destroy()` like this:

    internal static void Destroy<T>(ref T obj)
        where T : Object
    {
        if (obj == null) return;

        if (Application.isPlaying)
            Object.Destroy(obj);
        else
            Object.DestroyImmediate(obj);

        obj = null;
    }

and then adding the keyword `ref` to every call.

**Comment by sasa42** [comment]
Hi,
similiar behaviour in

Unity_2019_1_14f1
and
Unity_2019_2_1f1
with
Klak_Spout  v0.2.4

on a simple sender and receiver scene.
The Flicker from high frequence only happens in PlayMode.

**Comment by sasa42** [comment]
Thanks for the fixes.
Is there a recommendation for one of the 3 methods
and could one ofthem be integrated in an new release?

**Comment by keijiro** [comment]
Thank you very much for suggesting the fix. I applied it in 7eb9fd5
