### ISSUE TITLE
The plugin doesn't work with Unity 2019.3.6f1. Anyone experiencing the same?

### ISSUE THREAD

**Issue by Filmengineers** [keijiro/KlakSpout#50]
The spout receiver shows the "Sender IDs" in the drop down. But it doesn't receive anything from the sender to render texture.?

**Comment by eduardfrigola** [comment]
I found someone with the same problem, same symptoms, but with Unity 2019.3.7f1 and the fix was going to spout configure tool /SPOUTSETTINGS/SpoutSettings. And selecting Nvidia optimus mode to: "high performance" and/or changing spout sharing mode to GPU, as seen in this forum post: https://spout.zeal.co/forums/topic/spout-error-cannot-create-directxopengl-interop/

Maybe it is not the same problem as you are having, but can you try those?

**Comment by Filmengineers** [comment]
It worked! Thanks a ton!
